In [4]:
import numpy as np
import ciropt as co

In [25]:
n = 200


for _ in range(10):
    for symm in [True, False]:
        A = np.random.randn(n, n)
        if symm: A = A + A.T

        A_plus, A_minus = co.matrix_to_diff_psd(A)
        assert np.allclose(A, A_plus - A_minus), print(np.linalg.norm(A - (A_plus - A_minus), ord='fro'))

print("PASSED")

PASSED


In [18]:
A = co.symm_prod_one_hot(7, 4, 3)
A_plus, A_minus = co.matrix_to_diff_psd(A)
assert np.allclose(A, A_plus - A_minus), print(np.linalg.norm(A - (A_plus - A_minus), ord='fro'))

In [19]:
A

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [20]:
evals, V = np.linalg.eigh(A)
inv_V = np.linalg.inv(V)
assert np.allclose(A, (evals * V) @ inv_V)

In [21]:
A_plus, A_minus, A

(array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.25, 0.25, 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]),
 array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]]),
 array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0.5, 0. , 0. , 